# Generated by Django 5.1.15 on 2026-01-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0024_alter_profile_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="volunteer_opt_in",
            field=models.BooleanField(
                default=False,
                help_text="Recieve news about volunteer opportunities with Philly Bike Action.",
                verbose_name="Volunteering",
            ),
        ),
    ]
