# Generated by Django 5.1.15 on 2026-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_scheduledevent_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsignin',
            name='council_district',
        ),
        migrations.RemoveField(
            model_name='eventsignin',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='scheduledevent',
            name='districts',
        ),
        migrations.AddField(
            model_name='eventsignin',
            name='volunteer_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
