# Generated by Django 4.2.13 on 2024-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facets", "0005_custom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custom",
            name="properties",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
