# Generated by Django 5.1.14 on 2026-01-14 00:00

import wagtail.admin.forms.choosers
import wagtail.fields
from django.db import migrations

import cms.models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0017_postscontainerpage_posts_per_page_postpagetag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsstreampage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("card", 4),
                    ("paragraph", 6),
                    ("html", 7),
                    ("table", 8),
                    ("newsletter_signup", 9),
                    ("display_card_block", 12),
                    ("button", 26),
                ],
                block_lookup={
                    0: ("wagtail.images.blocks.ImageBlock", [], {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("right", "Right")]},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("image_side", 1), ("header", 2), ("text", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("left", "Left"), ("center", "Center"), ("right", "Right")]},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("alignment", 5), ("paragraph", 3)]],
                        {
                            "features": [
                                "anchor-identifier",
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                                "code",
                                "blockquote",
                            ]
                        },
                    ),
                    7: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    8: (
                        "wagtail.contrib.table_block.blocks.TableBlock",
                        (),
                        {
                            "table_options": {
                                "contextMenu": [
                                    "row_above",
                                    "row_below",
                                    "---------",
                                    "col_left",
                                    "col_right",
                                    "---------",
                                    "remove_row",
                                    "remove_col",
                                    "---------",
                                    "undo",
                                    "redo",
                                    "---------",
                                    "copy",
                                    "cut",
                                    "---------",
                                    "alignment",
                                ],
                                "editor": "text",
                                "renderer": "html",
                            }
                        },
                    ),
                    9: ("wagtail.blocks.StructBlock", [[]], {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": cms.models.get_collections, "label": "Collection to display"},
                    ),
                    11: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("collection", 10),
                                ("card_count_description", 2),
                                ("random_order", 11),
                            ]
                        ],
                        {},
                    ),
                    13: ("wagtail.blocks.CharBlock", (), {}),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("file", "File"),
                                ("custom_url", "Custom URL"),
                                ("email", "Email"),
                                ("anchor", "Anchor"),
                                ("phone", "Phone"),
                            ],
                            "classname": "link_choice_type_selector",
                            "label": "Link to",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"form_classname": "page_link", "label": "Page", "required": False},
                    ),
                    16: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"form_classname": "file_link", "label": "File", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "custom_url_link url_field",
                            "label": "Custom URL",
                            "max_length": 300,
                            "required": False,
                            "validators": [
                                wagtail.admin.forms.choosers.URLOrAbsolutePathValidator()
                            ],
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "anchor_link",
                            "label": "#",
                            "max_length": 300,
                            "required": False,
                        },
                    ),
                    19: ("wagtail.blocks.EmailBlock", (), {"required": False}),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "phone_link",
                            "label": "Phone",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "form_classname": "new_window_toggle",
                            "label": "Open in new window",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_to", 14),
                                ("page", 15),
                                ("file", 16),
                                ("custom_url", 17),
                                ("anchor", 18),
                                ("email", 19),
                                ("phone", 20),
                                ("new_window", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("pink", "Pink"), ("green", "Green")]},
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("full", "Full"), ("half", "Half")]},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": (
                                "A FontAwesome icon name, see <a "
                                'href="https://fontawesome.com/search?ic=free"'
                                ">here</a> for list of options"
                            ),
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 13), ("url", 22), ("color", 23), ("width", 24), ("icon", 25)]],
                        {},
                    ),
                },
            ),
        ),
    ]
