# Generated by Django 5.1.15 on 2026-09-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailblasts', '0006_add_event_rsvp_target_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailblasttargetnode',
            name='primitive_type',
            field=models.CharField(blank=True, choices=[('all_profiles', 'All profiles'), ('district', 'District'), ('rco', 'Registered Community Organization'), ('zip_code', 'Zip Code'), ('ward', 'Ward'), ('division', 'Division'), ('geojson', 'GeoJSON boundary'), ('petition', 'Petition signers'), ('event_rsvp', 'Event RSVPs'), ('event_signin', 'Event sign-ins'), ('legacy', 'Legacy/custom targeting'), ('volunteers', 'Volunteering Opt Ins')], max_length=32),
        ),
    ]
