# Generated by Django 5.1.15 on 2026-07-30 00:14

import community_fund.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityActionFundApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("draft", models.BooleanField(default=False)),
                ("data", models.JSONField()),
                ("markdown", models.TextField(blank=True)),
                ("thread_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "Approved"), ("declined", "Declined")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityActionFundApplicationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
            ],
            options={
                "ordering": ("-starts_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="community_fund_period_ends_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunityActionFundSupportingMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=community_fund.models.community_action_fund_supporting_material_upload_to
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_materials",
                        to="community_fund.communityactionfundapplication",
                    ),
                ),
            ],
        ),
    ]
