# Generated by Django 5.1.8 on 2025-09-06 15:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0028_add_wagtail_campaign_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("petition", 4), ("image", 5), ("html", 6)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "campaigns.wagtail_models.PetitionChooserBlock",
                        (),
                        {"help_text": "Select a petition to display", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": (
                                "Override the petition's display settings for this campaign"
                            ),
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": (
                                "Display this petition on the campaign page "
                                "(only used if override is checked)"
                            ),
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("petition", 1),
                                ("override_display", 2),
                                ("display_on_campaign_page", 3),
                            ]
                        ],
                        {},
                    ),
                    5: ("wagtail.images.blocks.ImageBlock", [], {}),
                    6: ("wagtail.blocks.RawHTMLBlock", (), {}),
                },
            ),
        ),
    ]
