---
name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /var/lib/docker/buildkit
          key: ${{ runner.os }}-buildkit-${{ hashFiles('Dockerfile.dev', 'requirements.txt', 'requirements/**') }}
          restore-keys: |
            ${{ runner.os }}-buildkit-

      - name: Cache buildkit mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "root-npm": "/root/.npm",
              "user-cache-pip": "/home/user/.cache/pip"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Run lint
        run: make lint
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /var/lib/docker/buildkit
          key: ${{ runner.os }}-buildkit-${{ hashFiles('Dockerfile.dev', 'requirements.txt', 'requirements/**') }}
          restore-keys: |
            ${{ runner.os }}-buildkit-

      - name: Cache buildkit mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-map: |
            {
              "var-cache-apt": "/var/cache/apt",
              "var-lib-apt": "/var/lib/apt",
              "root-npm": "/root/.npm",
              "user-cache-pip": "/home/user/.cache/pip"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Run tests
        run: make test
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
